### ISSUE TITLE
Running Discord with Box64

### ISSUE THREAD

**Issue by rekomodo** [ptitSeb/box64#103] opened 2021-08-24 01:37 UTC
```
Box64 with Dynarec v0.1.3 39f2b50 built on Aug 23 2021 17:58:25
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 28 Env var
Looking for ./Discord
Using emulated libffmpeg.so
Using native(wrapped) libdl.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using emulated /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
Using native(wrapped) libX11.so.6
Using native(wrapped) libX11-xcb.so.1
Using native(wrapped) libxcb.so.1
Using emulated /usr/lib/x86_64-linux-gnu/libxcb-dri3.so.0
Using native(wrapped) libXcomposite.so.1
Using native(wrapped) libXcursor.so.1
Using native(wrapped) libXdamage.so.1
Using native(wrapped) libXext.so.6
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libXfixes.so.3
Using native(wrapped) libXi.so.6
Using native(wrapped) libXrender.so.1
Using native(wrapped) libXtst.so.6
Using emulated /usr/lib/x86_64-linux-gnu/libnss3.so
Using emulated /usr/lib/x86_64-linux-gnu/libnssutil3.so
Using emulated /usr/lib/x86_64-linux-gnu/libsmime3.so
Using emulated /usr/lib/x86_64-linux-gnu/libnspr4.so
Using native(wrapped) libatk-1.0.so.0
Using native(wrapped) libatk-bridge-2.0.so.0
Using native(wrapped) libSM.so.6
Using native(wrapped) libICE.so.6
Using native(wrapped) libdbus-1.so.3
Using emulated /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
Using native(wrapped) libpangocairo-1.0.so.0
Using native(wrapped) libpango-1.0.so.0
Using native(wrapped) libgnutls.so.30
Using emulated /usr/lib/x86_64-linux-gnu/libpcre.so.1
Using emulated /usr/lib/x86_64-linux-gnu/libffi.so.6
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libcairo.so.2
Using native(wrapped) libm.so.6
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libexpat.so.1
Using emulated /usr/lib/x86_64-linux-gnu/libdrm.so.2
Using emulated /usr/lib/x86_64-linux-gnu/libgbm.so.1
Using native(wrapped) libXss.so.1
Using native(wrapped) libasound.so.2
Using native(wrapped) libatspi.so.0
Using native(wrapped) libcups.so.2
Using emulated /usr/lib/x86_64-linux-gnu/libgcc_s.so.1
Using emulated /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0
Using native(wrapped) libz.so.1
Using emulated /usr/lib/x86_64-linux-gnu/libselinux.so.1
Using native(wrapped) libresolv.so.2
Using emulated /usr/lib/x86_64-linux-gnu/libmount.so.1
Using emulated /usr/lib/x86_64-linux-gnu/libpcre2-8.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libblkid.so.1
Using native(wrapped) libuuid.so.1
Using emulated /usr/lib/x86_64-linux-gnu/libplc4.so
Using emulated /usr/lib/x86_64-linux-gnu/libplds4.so
Using native(wrapped) libpng16.so.16
Using emulated /usr/lib/x86_64-linux-gnu/libcairo-gobject.so.2
Using emulated /usr/lib/x86_64-linux-gnu/libwayland-client.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libepoxy.so.0
Using native(wrapped) libpangoft2-1.0.so.0
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libXinerama.so.1
Using native(wrapped) libxkbcommon.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libwayland-cursor.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libwayland-egl.so.1
Using emulated /usr/lib/x86_64-linux-gnu/libpixman-1.so.0
Using native(wrapped) libxcb-shm.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libxcb-render.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libwayland-server.so.0
../../third_party/tcmalloc/chromium/src/tcmalloc.cc:337] Attempt to free invalid pointer 0x656631b0 
6101|SIGSEGV @0x7f6a86c058 (???(0x7f6a86c058)) (x64pc=0x7f7374fb44/./Discord:"???", rsp=0x7f71c13310, stack=0x7f71414000:0x7f71c14000 own=(nil) fp=0x7f71c13460), for accessing 0x39 (code=1/prot=0), db=0x6569e800(0x7f6a86c048:0x7f6a86c094/0x7f7374fb40:0x7f7374fb4e/???:clean, hash:6ed19c28/6ed19c28) handler=(nil)
Segmentation fault
```

**Comment by rajdakin** [comment] 2024-07-08 13:06
Looks like a duplicate of #42.

**Closed by rajdakin** 2024-07-08 13:06 UTC
