### ISSUE TITLE
Wine64 error, could not exec wineserver

### ISSUE THREAD

**Issue by Spagett1** [ptitSeb/box64#208] opened 2022-01-11 15:25 UTC
im trying to run a wine program on my computer using box64 however i recieve the following error
```
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096
Box64 with Dynarec v0.1.7 9bf7185 built on Jan 11 2022 15:29:23
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 31 Env var
Looking for /usr/bin/wine64
argv[1]="/opt/drive2/SC64/drive_c/Program Files (x86)/Starcraft/StarCraft.exe"
Using native(wrapped) libpthread.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) librt.so.1
Using emulated /opt/wine-devel/bin/../lib64/wine/ntdll.so
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096
Box64 with Dynarec v0.1.7 9bf7185 built on Jan 11 2022 15:29:23
BOX64: Wine64 detected, WINEPRELOADRESERVE=""
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 32 Env var
Looking for /opt/wine-devel/bin/wine64
argv[1]="/opt/drive2/SC64/drive_c/Program Files (x86)/Starcraft/StarCraft.exe"
Using native(wrapped) libpthread.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) librt.so.1
Using emulated /opt/wine-devel/bin/../lib64/wine/ntdll.so
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
err:environ:read_nls_file failed to load 10/0
wine: could not exec wineserver
```
i recieve the same error attempting to run notepad++ which i downloaded to check it wasnt just an issue with wine. the wine version in use is 5.21. Thanks

Note: my system doesnt support 32bit (and as of such box86) however since im using wine64 i dont think that will be an issue (not for this problem at least)

**Comment by ptitSeb** [comment] 2022-01-11 15:42
StarCraft is a 32bits, so it needs a 32bits subsystem. Without box86, you cannot run it with box for now, sorry.

Wine do like linux, it use the 32bits subsystem to run 32bits program.

**Comment by Laar3** [comment] 2022-01-11 20:48
i guess i was hoping that it would work since on my laptop using `wine64` and a 64bit prefix worked but i guess it was using 32bit stuff in the background, thanks.

Regardless the issue is not limited to starcraft, it happens in notepad++ too which is a 64bit program.

**Comment by rajdakin** [comment] 2024-07-08 14:39
Is this fixed now?
Also, 32-bits Windows apps can now be run using the new WoW64-enabled builds of Wine 64-bits (though how reliable this is is another question).

**Comment by LukeShortCloud** [comment] 2024-10-31 13:32
I ran into the error `wine: could not exec wineserver` recently and can confirm that any of the following address this issue:
- Installing Box86
- Building Box64 with Box32 support
- Using Box86 with Wine WoW64

Closing as complete.

**Closed by LukeShortCloud** 2024-10-31 13:32 UTC
