### ISSUE TITLE
Dwarf Fortress

### ISSUE THREAD

**Issue by rekomodo** [ptitSeb/box64#101] opened 2021-08-23 07:04 UTC
dwarf fortress won't launch
command: sudo ./df

```
Box64 with Dynarec v0.1.3 5bca9b5 built on Aug 21 2021 22:51:13
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 31 Env var
Looking for ./libs/Dwarf_Fortress
Using native(wrapped) libSDL-1.2.so.0
Using native(wrapped) libm.so.6
Using native(wrapped) libdl.so.2
Using native(wrapped) librt.so.1
Using emulated /home/komodo/Downloads/df_47_05_linux/df_linux/libs/libgraphics.so
Using emulated /usr/lib/x86_64-linux-gnu/libstdc++.so.6
Using emulated /home/komodo/Downloads/df_47_05_linux/df_linux/libs/libgcc_s.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
Using native(wrapped) libSDL_image-1.2.so.0
Using native(wrapped) libz.so.1
Using native(wrapped) libGLU.so.1
Using native(wrapped) libGL.so.1
Using native(wrapped) libSDL_ttf-2.0.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0
Using native(wrapped) libpangocairo-1.0.so.0
Using native(wrapped) libpango-1.0.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
Using native(wrapped) libgnutls.so.30
Using emulated /usr/lib/x86_64-linux-gnu/libpcre.so.1
Using emulated /usr/lib/x86_64-linux-gnu/libffi.so.6
Using native(wrapped) libX11.so.6
Using native(wrapped) libXfixes.so.3
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libatk-1.0.so.0
Using native(wrapped) libcairo.so.2
Using emulated /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
Using native(wrapped) libpangoft2-1.0.so.0
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libXrender.so.1
Using native(wrapped) libXinerama.so.1
Using native(wrapped) libXext.so.6
Using native(wrapped) libXi.so.6
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libXcursor.so.1
Using native(wrapped) libXcomposite.so.1
Using native(wrapped) libXdamage.so.1
Using emulated /usr/lib/x86_64-linux-gnu/libselinux.so.1
Using native(wrapped) libresolv.so.2
Using emulated /usr/lib/x86_64-linux-gnu/libmount.so.1
Using emulated /usr/lib/x86_64-linux-gnu/libpcre2-8.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libblkid.so.1
Using native(wrapped) libuuid.so.1
Using native(wrapped) libpng16.so.16

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.335: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.343: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.344: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.346: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.347: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.347: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.348: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.348: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.349: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.349: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.349: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.350: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.350: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.350: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.351: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.351: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.352: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.352: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.353: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.353: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.354: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.354: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.355: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.355: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.355: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.356: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.356: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.357: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.360: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.361: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.367: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.367: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.368: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.368: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.371: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:433): Gtk-WARNING **: 02:59:41.371: Unable to locate theme engine in module_path: "murrine",
Using emulated /usr/lib/x86_64-linux-gnu/libgail.so
Using emulated /usr/lib/x86_64-linux-gnu/libgailutil.so.18
Using emulated /usr/lib/x86_64-linux-gnu/libatk-bridge.so
Using native(wrapped) libatk-bridge-2.0.so.0
Using native(wrapped) libSM.so.6
Using native(wrapped) libICE.so.6
Using native(wrapped) libatspi.so.0
Using native(wrapped) libdbus-1.so.3
Using emulated /usr/lib/x86_64-linux-gnu/libcanberra-gtk-module.so
Using emulated /usr/lib/x86_64-linux-gnu/libcanberra-gtk.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libcanberra.so.0
Using native(wrapped) libvorbisfile.so.3
Using emulated /usr/lib/x86_64-linux-gnu/libtdb.so.1
Using emulated /usr/lib/x86_64-linux-gnu/libltdl.so.7
Error: PltResolver: Symbol atk_object_factory_get_type(ver 0: atk_object_factory_get_type) not found, cannot apply R_X86_64_JUMP_SLOT 0x7f7a552180 (0x7f7a50e306) in /usr/lib/x86_64-linux-gnu/libgail.so
```

**Comment by rekomodo** [comment] 2021-08-23 22:00
```
Box64 with Dynarec v0.1.3 39f2b50 built on Aug 23 2021 17:58:25
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 31 Env var
Looking for ./libs/Dwarf_Fortress
Using native(wrapped) libSDL-1.2.so.0
Using native(wrapped) libm.so.6
Using native(wrapped) libdl.so.2
Using native(wrapped) librt.so.1
Using emulated /home/komodo/Downloads/df_47_05_linux/df_linux/libs/libgraphics.so
Using emulated /usr/lib/x86_64-linux-gnu/libstdc++.so.6
Using emulated /home/komodo/Downloads/df_47_05_linux/df_linux/libs/libgcc_s.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
Using native(wrapped) libSDL_image-1.2.so.0
Using native(wrapped) libz.so.1
Using native(wrapped) libGLU.so.1
Using native(wrapped) libGL.so.1
Using native(wrapped) libSDL_ttf-2.0.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0
Using native(wrapped) libpangocairo-1.0.so.0
Using native(wrapped) libpango-1.0.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
Using native(wrapped) libgnutls.so.30
Using emulated /usr/lib/x86_64-linux-gnu/libpcre.so.1
Using emulated /usr/lib/x86_64-linux-gnu/libffi.so.6
Using native(wrapped) libX11.so.6
Using native(wrapped) libXfixes.so.3
Using native(wrapped) libxcb.so.1
Using native(wrapped) libXau.so.6
Using native(wrapped) libXdmcp.so.6
Using native(wrapped) libatk-1.0.so.0
Using native(wrapped) libcairo.so.2
Using emulated /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
Using native(wrapped) libpangoft2-1.0.so.0
Using native(wrapped) libfontconfig.so.1
Using native(wrapped) libfreetype.so.6
Using native(wrapped) libXrender.so.1
Using native(wrapped) libXinerama.so.1
Using native(wrapped) libXext.so.6
Using native(wrapped) libXi.so.6
Using native(wrapped) libXrandr.so.2
Using native(wrapped) libXcursor.so.1
Using native(wrapped) libXcomposite.so.1
Using native(wrapped) libXdamage.so.1
Using emulated /usr/lib/x86_64-linux-gnu/libselinux.so.1
Using native(wrapped) libresolv.so.2
Using emulated /usr/lib/x86_64-linux-gnu/libmount.so.1
Using emulated /usr/lib/x86_64-linux-gnu/libpcre2-8.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libblkid.so.1
Using native(wrapped) libuuid.so.1
Using native(wrapped) libpng16.so.16

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.045: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.054: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.054: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.057: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.057: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.058: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.058: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.058: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.059: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.059: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.059: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.059: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.060: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.060: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.060: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.061: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.062: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.062: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.063: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.063: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.063: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.064: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.064: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.065: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.065: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.066: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.066: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.067: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.071: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.072: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.076: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.076: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.077: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.077: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.079: Unable to locate theme engine in module_path: "murrine",

(Dwarf_Fortress:19746): Gtk-WARNING **: 17:59:27.080: Unable to locate theme engine in module_path: "murrine",
Using emulated /usr/lib/x86_64-linux-gnu/libgail.so
Using emulated /usr/lib/x86_64-linux-gnu/libgailutil.so.18
Using emulated /usr/lib/x86_64-linux-gnu/libatk-bridge.so
Using native(wrapped) libatk-bridge-2.0.so.0
Using native(wrapped) libSM.so.6
Using native(wrapped) libICE.so.6
Using native(wrapped) libatspi.so.0
Using native(wrapped) libdbus-1.so.3
Using emulated /usr/lib/x86_64-linux-gnu/libcanberra-gtk-module.so
Using emulated /usr/lib/x86_64-linux-gnu/libcanberra-gtk.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0
Using emulated /usr/lib/x86_64-linux-gnu/libcanberra.so.0
Using native(wrapped) libvorbisfile.so.3
Using emulated /usr/lib/x86_64-linux-gnu/libtdb.so.1
Using emulated /usr/lib/x86_64-linux-gnu/libltdl.so.7
Warning, jumping to a no-block address 0x7faa90ca68 from 0x7fa66d12f8 (db=0x65527de0, x64addr=0x7fac8059d8)
19746|Warning, ignoring unsupported Int 3 call @0x7faa90ca31
19746|0x7faa90ca31: Unimplemented Opcode (CC) C4 FF 97 73 E2 10 91 E2 FF FF D0 42 60 23 91
```

**Comment by ptitSeb** [comment] 2021-09-18 19:19
I got Dwarf Fortress (classic version from 28th on january 2021 I think), I have wrapped the needed library.

**Comment by SlyEcho** [comment] 2021-09-19 10:59
I'm still getting a crash with an illegal instruction.

I turned off the sound in the game.

The game is using its own libgcc_s and libstdc++ however it makes no difference.

Configuration: -DARM_DYNAREC=ON -DCMAKE_BUILD_TYPE=Release -DRK3399=ON

System: Manjaro ARM

```
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL PageSize:4096
Box64 with Dynarec v0.1.5 ec2eadd built on Sep 19 2021 13:47:44
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 61 Env var
Looking for ./libs/Dwarf_Fortress
Using native(wrapped) libSDL-1.2.so.0
Using native(wrapped) libm.so.6
Using native(wrapped) libdl.so.2
Using native(wrapped) librt.so.1
Using emulated /home/henri/games/df_linux/libs/libgraphics.so
Using emulated /home/henri/games/df_linux/libs/libstdc++.so.6
Using emulated /home/henri/games/df_linux/libs/libgcc_s.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) libgtk-x11-2.0.so.0
Using native(wrapped) libgdk-x11-2.0.so.0
Using native(wrapped) libgobject-2.0.so.0
Using native(wrapped) libglib-2.0.so.0
Using native(wrapped) libgio-2.0.so.0
Using native(wrapped) libgmodule-2.0.so.0
Using native(wrapped) libgdk_pixbuf-2.0.so.0
Using native(wrapped) libpangocairo-1.0.so.0
Using native(wrapped) libpango-1.0.so.0
Using native(wrapped) libSDL_image-1.2.so.0
Using native(wrapped) libz.so.1
Using native(wrapped) libGLU.so.1
Using native(wrapped) libGL.so.1
Using native(wrapped) libSDL_ttf-2.0.so.0

(Dwarf_Fortress:10735): Gtk-WARNING **: 13:49:19.536: Unable to locate theme engine in module_path: "adwaita",
Loading bindings from data/init/interface.txt
New window size: 1000x480
Font size: 8x12
Resizing grid to 125x40
Resizing font to 8x12
10735|SIGILL @0xffff8ca70100 (???(0xffff8ca70100)) (x64pc=0x980cb020/???:"???", rsp=0xffff8da19298, stack=0xffff8d21a000:0xffff8da1a000 own=(nil) fp=0x1a9fc20), for accessing 0xffff8ca70100 (code=1/prot=c7), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil) opcode=FF 25 EA C1 31 00 68 5B (CC 53 43 90 76)
Illegal instruction (core dumped)
```

**Comment by ptitSeb** [comment] 2021-09-19 11:42
Strange. I tried DwarfFortress with that same commit and it was working fine for me (with sound). It indeed use it's own libgcc_s and libstdc++ on my side too.

Try to run with `BOX64_LOG=2` to see if a specific wrapped function call is making it crash.

**Comment by SlyEcho** [comment] 2021-09-19 15:52
OK, used the log flag:

```
...
pages of output ...
...
35312|0xffffba07e222: Calling memset (/usr/lib/libc.so.6)(0x73EC2D10, 0x0, 0x9C40, ...) => return 0x73EC2D10
35312|0xffffb9c0fdad: Calling my_malloc (/usr/local/bin/box64)(0x1388, 0x0, 0x9C40, ...) => return 0x73ECC960
35312|0xffffba07e23b: Calling memset (/usr/lib/libc.so.6)(0x73ECC960, 0x0, 0x1388, ...) => return 0x73ECC960
35312|0xffffb9c0fdad: Calling my_malloc (/usr/local/bin/box64)(0x1388, 0x0, 0x1388, ...) => return 0x73ECDCF0
35312|0xffffba07e254: Calling memset (/usr/lib/libc.so.6)(0x73ECDCF0, 0x0, 0x1388, ...) => return 0x73ECDCF0
35312|0xffffb9c0fdad: Calling my_malloc (/usr/local/bin/box64)(0x1388, 0x0, 0x1388, ...) => return 0x73ECF080
35312|0xffffba07e26d: Calling memset (/usr/lib/libc.so.6)(0x73ECF080, 0x0, 0x1388, ...) => return 0x73ECF080
35312|0xffffb9c0fdad: Calling my_malloc (/usr/local/bin/box64)(0x1388, 0x0, 0x1388, ...) => return 0x73ED0410
35312|0xffffba07e286: Calling memset (/usr/lib/libc.so.6)(0x73ED0410, 0x0, 0x1388, ...) => return 0x73ED0410
 ...  =>PltResolver: Addr=0x7186daf0, Slot=87 Return=0xffffba0871dd: elf is /home/henri/games/df_linux/libs/libgraphics.so (VerSym=0x2f024)
            Apply Global R_X86_64_JUMP_SLOT 0xffffba3962d0 with sym=_ZN13ttf_managerst4initEii(ver 1: _ZN13ttf_managerst4initEii) (0xffffba07a0c6 -> 0xffffba154fe0 / /home/henri/games/df_linux/libs/libgraphics.so)
 return 0x0
 ...  =>PltResolver: Addr=0x7186daf0, Slot=493 Return=0xffffba154ffe: elf is /home/henri/games/df_linux/libs/libgraphics.so (VerSym=0x2f024)
            Apply Global R_X86_64_JUMP_SLOT 0xffffba396f80 with sym=TTF_WasInit(ver 0: TTF_WasInit) (0xffffba07ba26 -> 0x71a4c0c0 / (noelf))
 return 0x0
35312|0xffffba154ffe: Calling TTF_WasInit (/usr/lib/libSDL_ttf-2.0.so.0)(0xFFFFBA67A640, 0xC, 0x8, ...) => return 0x0
 ...  =>PltResolver: Addr=0x7186daf0, Slot=144 Return=0xffffba155231: elf is /home/henri/games/df_linux/libs/libgraphics.so (VerSym=0x2f024)
            Apply Global R_X86_64_JUMP_SLOT 0xffffba396498 with sym=TTF_Init(ver 0: TTF_Init) (0xffffba07a456 -> 0x71a4c080 / (noelf))
 return 0x0
35312|0xffffba155231: Calling TTF_Init (/usr/lib/libSDL_ttf-2.0.so.0)(0xFFFFBA67A640, 0xC, 0x8, ...) => return 0x0
35312|0xffffba1550ad: Calling memset (/usr/lib/libc.so.6)(0x71AEAB70, 0x0, 0x58, ...) => return 0x71AEAB70
35312|0xffffba15511c: Calling memset (/usr/lib/libc.so.6)(0x71AEB150, 0x0, 0x58, ...) => return 0x71AEB150
 ...  =>PltResolver: Addr=0x7186daf0, Slot=91 Return=0xffffba15514e: elf is /home/henri/games/df_linux/libs/libgraphics.so (VerSym=0x2f024)
            Apply Global R_X86_64_JUMP_SLOT 0xffffba3962f0 with sym=TTF_OpenFont(ver 0: TTF_OpenFont) (0xffffba07a106 -> 0x71a4c020 / (noelf))
 return 0xC
35312|0xffffba15514e: Calling TTF_OpenFont (/usr/lib/libSDL_ttf-2.0.so.0)(0xFFFFBA177E75, 0x14, 0x58, ...) =>35312|SIGBUS @0xffffba15514e (???(0xffffba15514e)) (x64pc=0x71a4c033/???:"???", rsp=0xffffbb023298, stack=0xffffba824000:0xffffbb024000 own=(nil) fp=0x1a9fc20), for accessing 0xffffba15514e (code=1/prot=c7), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil) x86opcode=C3 00 00 00 00 00 00 00
Bus error (core dumped)
```

**Comment by ptitSeb** [comment] 2021-09-19 17:07
So, the error occurs durring `TTF_OpenFont(...)` call. Strange. Maybe it tries to load a font that doesn't exist or is corrupted somehow?

**Comment by SlyEcho** [comment] 2021-09-20 13:27
There is no error with a fresh debian sid chroot. I'm just thinking of how to trace the error...

**Comment by SlyEcho** [comment] 2021-09-24 20:44
I got it to work.

It appears that I had the SDL2 version of SDL_ttf installed as the same name as the SDL1.2 version of SDL_ttf.

I tried to use BOX64_LD_LIBRARY_PATH but this is limited for only x86_64 libraries, I guess.

**Comment by rajdakin** [comment] 2024-07-08 13:04
@rekomodo Can you confirm that the issue is fixed now?

**Comment by LukeShortCloud** [comment] 2024-11-01 13:51
The solution for Dwarf Fortress appears to be to use SDL 2 (not SDL 1.2) system packages. Closing as resolved.

**Closed by LukeShortCloud** 2024-11-01 13:51 UTC
