### ISSUE TITLE
recent zoom client not working

### ISSUE THREAD

**Issue by gadido30** [ptitSeb/box64#451] opened 2022-11-16 13:38 UTC
Hi All

I have downloaded latest zoom client, 
When I tired to run zoom client , it show an error: "libffmpeg.so" is missing, any idea?

The old zoom client work perfect

**Comment by theofficialgman** [comment] 2022-11-19 00:15
don't cross list on box64 (from pi-apps). this isn't a box64 issue and is an issue caused by upstream zoom that needs pi-apps packaging changes

**Comment by ptitSeb** [comment] 2023-03-05 20:29
Please update to latest box64 version and try again, it should work now, and this ticket can be closed.

**Comment by LukeShortCloud** [comment] 2024-11-02 18:51
Closing as resolved.

**Closed by LukeShortCloud** 2024-11-02 18:51 UTC
