### ISSUE TITLE
Can we run x86_64 flatpak packages with Box64

### ISSUE THREAD

**Issue by zcheese1** [ptitSeb/box64#2131] opened 2024-12-09 14:56 UTC
Hello, 
sorry for asking this, but can we install flatpak packages (x86_64) by Box64? [In aarch64 host, I am trying to install Roblox Studio via vinegarhq, which is available in flatpak] Thanks again.

**Comment by m1m1k4tz** [comment] 2024-12-09 15:58
This is a duplicate of https://github.com/ptitSeb/box64/issues/1361. That's what you're looking for 👍

**Closed** 2024-12-10 06:12 UTC
