### ISSUE TITLE
Can it work on android? Aarch64

### ISSUE THREAD

**Issue by klaxons1** [ptitSeb/box64#64] opened 2021-07-18 17:19 UTC

**Comment by ptitSeb** [comment] 2021-07-18 18:39
Not directly for now. But it can run on proot/termux/whatever solution to get linux on android.

**Comment by davie504** [comment] 2021-07-18 19:09
But porting to android in your ToDo?

**Comment by leapofazzam123** [comment] 2021-07-26 14:47
I tried to compile box64 inside termux in my aarch64 phone, and i got a lot of errors from clang. One of them was `use of undeclared identifier 'info'`

**Comment by ptitSeb** [comment] 2021-07-26 14:53
I haven't tried building box64 with clang. Can you use gcc instead?

**Comment by leapofazzam123** [comment] 2021-08-02 03:01
> I haven't tried building box64 with clang. Can you use gcc instead?

I tried using gcc from it's pointless repo, but cmake fails, it might be related to this issue: termux/termux-packages#6960

![Screenshot_20210801-214440](https://user-images.githubusercontent.com/76893443/127798839-0268f253-83ba-4018-8bb2-3b421b7ba163.png)

**Comment by leapofazzam123** [comment] 2021-08-02 04:07
The only way I can bypass this is by replacing the line `include(Platform/Android/abi-${CMAKE_ANDROID_ARCH_ABI}-GNU)` with `include(Platform/Android/abi-arm64-v8a-GNU)` on `$PREFIX/share/cmake-3.21/Modules/Platform/Android-GNU.cmake`. And surprisingly enough, there isn't as many errors in GCC compared to Clang, but still, it's can't compile it on Termux

![Screenshot_20210802-110427](https://user-images.githubusercontent.com/76893443/127803043-a0de5c07-7d03-4e11-8c43-32df043b765b.png)

**Comment by leapofazzam123** [comment] 2021-08-02 04:11
There's this video but it uses proot https://youtu.be/TMV3Fp5YhTs

**Comment by leapofazzam123** [comment] 2021-08-02 04:11
I want to make it work on native termux, not just in a prooted linux distro

**Comment by leapofazzam123** [comment] 2021-08-02 04:15
Also why is this issue closed? Can someone reopen it again?

**Comment by ptitSeb** [comment] 2021-08-02 05:56
I have reopenned the issue. 
The issue is not realy cland/gcc here. It's Android. I didn't noticed this was the "Android" ticket. If you look at box86, the Android build has a lot of `#ifdef`'d parts, because Android is not 100% linux.

**Comment by oxr463** [comment] 2021-10-18 11:38
See also: https://github.com/termux/termux-packages/issues/7672

**Comment by ptitSeb** [comment] 2023-09-02 14:44
Box64 now have a ` ANDROID`  build profile, like box86. With this profile, box64 should be able to build with android NDK and run Android x86_64 binary (not linux x86_64 binary), like box86.

This build is untested, as Android support is minimum (it build, that's all that is checked)

**Comment by rajdakin** [comment] 2024-07-08 12:41
Can this be closed now?

**Comment by LukeShortCloud** [comment] 2024-10-31 13:17
Box64 has supported Android for a year now (and Termux/proots before that). Closing as complete.

**Closed by LukeShortCloud** 2024-10-31 13:17 UTC

**Comment by ksco** [comment] 2024-10-31 13:28
Side note: use Winlator if you're lazy, it uses box86/box64 under the hood.
