### ISSUE TITLE
Spotify Error loading libs

### ISSUE THREAD

**Issue by xboxones1** [ptitSeb/box64#1013] opened 2023-10-07 03:39 UTC
spotify version [1.2.20](http://repository.spotify.com/pool/non-free/s/spotify-client/) won't start
```
Error loading needed lib libayatana-appindicator3.so.1
Error loading needed lib libdbusmenu-glib.so.4
```

**Comment by ptitSeb** [comment] 2023-10-07 06:09
I have to check this new version I suppose.

**Comment by ptitSeb** [comment] 2023-10-10 12:19
Ok, I ave added those 2 wrapped lib (and fixed a few other stuff). Latest spotify seems to start fine now.

**Comment by xboxones1** [comment] 2023-10-10 14:29
Before authorization
`Error loading needed lib libgnome-keyring.so.0`
After authorization
```
5858|SIGSEGV @0xffffb31e2214 (__atomic_store (/lib/aarch64-linux-gnu/libatomic.so.1)) (x64pc=0x90013/???:"???", rsp=0x11624d788, stack=0x116050000:0x116250000 own=0x116050000 fp=0x11624d7c0), for accessing 0x1624d790 (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
RSP-0x20:0x0000ffff5c5cd3a0 RSP-0x18:0x0000ffff5c5cd3f0 RSP-0x10:0x0000000057f9f9e0 RSP-0x08:0x0000000000000176
RSP+0x00:0x0000000000ca864c RSP+0x08:0x0000000000000001 RSP+0x10:0x00000001c0000000 RSP+0x18:0x0000ffff5cf2feb8
RAX:0x0000000000000001 RCX:0x0000000000000005 RDX:0x000000011624d790 RBX:0x0000ffff5cf2fe70 
RSP:0x000000011624d788 RBP:0x000000011624d7c0 RSI:0x0000ffff5ce85330 RDI:0x0000000000000010 
 R8:0x0000000000000061  R9:0x0000000000000060 R10:0x0000000000000003 R11:0xf27a89c5f102c520 
R12:0x0000ffff5cf2feb8 R13:0x0000ffff5ce85310 R14:0x0000ffff5cf2fe70 R15:0x0000ffff5cf2fe98 
ES:0x002b CS:0x0033 SS:0x002b DS:0x002b FS:0x0043 GS:0x0053
Segmentation fault
```

**Comment by ptitSeb** [comment] 2023-10-10 14:34
I have noticed `libgnome-keyring.so.0` but I don't think it's needed (not sure, but for me, this is optionnal).

The segfault after authorization is more of a problem (I don't have an account, and don't plan of creating one). I'll check the signature of `__atomic_store` first.

**Comment by ptitSeb** [comment] 2023-10-10 14:38
Mmmm, signature looks good.
Can you run with `BOX64_ROLLING_LOG=1` and `BOX64_SHOWBT=1` to have the 16 last function called at the segfault, and the emulated+native backtrace. It might help.

**Comment by xboxones1** [comment] 2023-10-10 14:56
Log: [spotify.log](https://github.com/ptitSeb/box64/files/12858671/spotify.log)

**Comment by xboxones1** [comment] 2023-10-11 01:59
It works. Thanks.

**Comment by xboxones1** [comment] 2023-10-13 13:16
They updated to version 1.2.22 and it does not work after authorization
Log: [spotify.log](https://github.com/ptitSeb/box64/files/12893859/spotify.log)

**Comment by ptitSeb** [comment] 2023-10-13 13:59
I suppose it's an ABORT because malloc/free heap is corrupted? Loke like that with the log extract.

**Comment by xboxones1** [comment] 2023-10-13 14:22
ше цшер BOX64_ROLLING_LOG=1 and BOX64_SHOWBT=1

**Comment by xboxones1** [comment] 2023-10-13 14:37
The interface is trying to load the error later and then tries to boot again. Sometimes it loads and works if you wait for a long time.
Log: [spotify2.log](https://github.com/ptitSeb/box64/files/12894627/spotify2.log)

**Comment by xboxones1** [comment] 2023-11-03 07:38
After the latest commits, the old versions stopped working, the program interface does not load after authorization
Log: [spotify.log](https://github.com/ptitSeb/box64/files/13247646/spotify.log)

![1](https://github.com/ptitSeb/box64/assets/91512529/93f814a1-a0d4-4ac8-ad59-1adf61d31a1c)

**Comment by ptitSeb** [comment] 2023-11-03 09:27
I reproduce those strange dlopen error (I assume the segfault and the error you have are a consequence of that). I'll work on fixing this regression.

**Comment by ptitSeb** [comment] 2023-11-03 11:12
Ok, I think I found the regression. It should be fixed now with latest box64.

**Comment by ptitSeb** [comment] 2023-11-03 15:20
I don't see anything wrong with the logs there. Is the commit you posted the last one that work or just a random one that works?

**Comment by xboxones1** [comment] 2023-11-04 08:26
The commit is not random, I remember at what point it worked. I don’t know after which commit it stopped working, I’ll try several commits, maybe I’ll be able to identify the last working one, but this process is certainly not fast.

**Comment by ptitSeb** [comment] 2023-11-04 08:32
If you build box64 from source, you can use `git bisect` to help you doing the bisection to find the first failling commit fast.

**Comment by xboxones1** [comment] 2023-11-04 12:07
thanks for git bisect, I didn't know about this feature. The problematic commit has been found.
```
git bisect bad
cb2a623faa78b02b93b402f665030f6b75cdf0a9 is the first bad commit
commit cb2a623faa78b02b93b402f665030f6b75cdf0a9
Date:   Mon Oct 30 16:38:15 2023 +0100
```

**Comment by ptitSeb** [comment] 2023-11-04 13:11
Ah, SSE 4.2 support. I thought this PR was clean. Seems it's not.

**Comment by ptitSeb** [comment] 2023-11-04 15:06
Ok, I have pushed a fix in box64, if you can update and try again.

**Comment by xboxones1** [comment] 2023-11-05 05:11
Unfortunately it didn't help, it doesn't work

**Comment by ptitSeb** [comment] 2023-11-05 14:04
Ok, I think I found it this time. It should works with latest box64.

**Comment by xboxones1** [comment] 2023-11-05 15:24
Thanks, everything is fine now. Even the new version 1.22 works now.

**Closed** 2023-11-05 15:25 UTC
