### ISSUE TITLE
Unimplemented Opcode (FF) 64 66 0F 2E 04 C5 D0 F7 FF FF 89 C3 77 02 89

### ISSUE THREAD

**Issue by amitojsingh366** [ptitSeb/box64#325] opened 2022-06-14 16:40 UTC
Getting this error while trying to run the dedicated server for Ark: Survival Evolved, full log is pasted below:

```
Dynarec for ARM64, with extension: ASIMD AES CRC32 PMULL ATOMICS PageSize:4096
Box64 with Dynarec v0.1.8 30302a0 built on Jun  1 2022 13:52:07
Using default BOX64_LD_LIBRARY_PATH: ./:lib/:lib64/:x86_64/:bin64/:libs64/
Using default BOX64_PATH: ./:bin/
Counted 26 Env var
Looking for ./ShooterGameServer
argv[1]="LostIsland?listen?SessionName=Burgerland?ServerPassword=burger?ServerAdminPassword=burgerman69?AltSaveDirectoryName=lostisland"
argv[2]="-server"
argv[3]="-log"
Using native(wrapped) libpthread.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) librt.so.1
Using emulated /home/ubuntu/ark_server/ShooterGame/Binaries/Linux/../../../Engine/Binaries/Linux/libsteam_api.so
Using emulated libEOSSDK-Linux-Shipping.so
Using native(wrapped) libm.so.6
Using emulated /lib/x86_64-linux-gnu/libstdc++.so.6
Using emulated /lib/x86_64-linux-gnu/libgcc_s.so.1
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux-x86-64.so.2
Using native(wrapped) libresolv.so.2
Warning: Global Symbol _ZTH15GCrashErrorType not found, cannot apply R_X86_64_GLOB_DAT @0xffffa8ddaf10 ((nil)) in libEOSSDK-Linux-Shipping.so
Warning: Global Symbol _ZTH18GCrashErrorMessage not found, cannot apply R_X86_64_GLOB_DAT @0xffffa8ddaf08 ((nil)) in libEOSSDK-Linux-Shipping.so
Shutdown handler: initalize.
Using binned.
4.5.1-0+UE4 7038 3077 404 10
[S_API FAIL] SteamAPI_Init() failed; SteamAPI_IsSteamRunning() failed.
Using emulated steamclient.so
Error loading needed lib crashhandler.so
Warning: Cannot dlopen("crashhandler.so"/0xffff937ea8a8, 2)
Error loading needed lib /home/ubuntu/ark_server/ShooterGame/Binaries/Linux/steamservice.so
Warning: Cannot dlopen("/home/ubuntu/ark_server/ShooterGame/Binaries/Linux/steamservice.so"/0xffff81337df0, 2)
Error loading needed lib steamservice.so
Warning: Cannot dlopen("steamservice.so"/0xffff81337df0, 2)
Setting breakpad minidump AppID = 346110
Error loading needed lib /home/ubuntu/.steam/sdk64/libsteam.so
Warning: Cannot dlopen("/home/ubuntu/.steam/sdk64/libsteam.so"/0xffffa97f55c0, 2)
Error loading needed lib libsteam.so
Warning: Cannot dlopen("libsteam.so"/0xffffaa07954d, 2)
1581|0x1b36a6b: Unimplemented Opcode (FF) 64 66 0F 2E 04 C5 D0 F7 FF FF 89 C3 77 02 89
/home/buildbot/buildslave/steam_rel_client_linux64/build/src/tier1/../tier1/fileio.cpp (4008) : Assertion Failed: CFileWriterThread: pending file writer content_log.txt
/home/buildbot/buildslave/steam_rel_client_linux64/build/src/tier0/threadtools.cpp (1416) : Assertion Failed: Thread synchronization object is unuseable
Shutdown handler: cleanup.
```

**Comment by code-monet** [comment] 2022-07-02 23:58
Duplicate of #298

**Closed** 2022-07-03 08:30 UTC
