### ISSUE TITLE
Steam on raspberry pi 4

### ISSUE THREAD

**Issue by MeltingDiamond** [ptitSeb/box64#1611] opened 2024-06-23 23:55 UTC
I have a raspberry pi 4 b with the latest version raspberry pi os 64bit and I installed steam using pi-apps, then I restarted the pi like it told me to. But when I run steam in the console I get this error (Fatal error: Steam needs to be online to update, Please check internet connection). I have ethernet connected and am able to surfe the web.

I can download runtime_sniper_ubuntu12 manually (with the exact link the script uses), so I do not understand why it fails when the steam script tries to download it.

After the first run this is what the console says (can not download runtime_sniper_ubuntu12):
```~ $ steam
bin_steam.sh[2848]: Setting up Steam content in /home/adrian/.local/share/Steam
steam.sh[2848]: Running Steam on debian 12 64-bit
steam.sh[2848]: STEAM_RUNTIME is enabled by the user
setup.sh[2931]: Updating Steam runtime environment...
/home/adrian/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: linje 85: fant ikke kommando steam-runtime-identify-library-abi
run.sh[8811]: steam-runtime-identify-library-abi --ldconfig-paths failed, falling back to ldconfig
steam.sh[2848]: Can't find 'steam-runtime-check-requirements', continuing anyway
Debug level is 1
Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096 Running on Cortex-A72 with 4 Cores
Params database has 31 entries
Box86 with Dynarec v0.3.7 fc0b51f3 built on Jun 19 2024 23:33:09
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/:i686/
Using default BOX86_PATH: ./:bin/
Counted 67 Env var
Looking for /home/adrian/.local/share/Steam/ubuntu12_32/steam
steam detected
Apply RC params for steam
Applying BOX86_NOGTK=1
Applying BOX86_DYNAREC_STRONGMEM=1
Applying BOX86_DYNAREC_CALLRET=0
Applying BOX86_EMULATED_LIBS=libudev.so.0:libSDL2-2.0.so.0
argv[1]="-no-cef-sandbox"
argv[2]="steam://open/minigameslist"
Rename process to "steam"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Using native(wrapped) libX11.so.6
Using native(wrapped) libm.so.6
[2024-06-24 00:52:53] Startup - updater built Jan 13 2024 00:51:43
[2024-06-24 00:52:53] Startup - Steam Client launched with: '/home/adrian/.local/share/Steam/ubuntu12_32/steam' '-no-cef-sandbox' 'steam://open/minigameslist'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
Using native(wrapped) crashhandler.so
Using native(wrapped) libGL.so.1
[2024-06-24 00:52:55] Failed to load cached hosts file (File 'update_hosts_cached.vdf' not found), using defaults
[2024-06-24 00:52:55] Using the following download hosts for Public, Realm steamglobal
[2024-06-24 00:52:55] 1. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2024-06-24 00:52:55] Verifying installation...
[2024-06-24 00:52:55] Unable to read and verify install manifest /home/adrian/.local/share/Steam/package/steam_client_ubuntu12.installed
[2024-06-24 00:52:55] Verification complete
[2024-06-24 00:52:55] Downloading Update...
[2024-06-24 00:52:55] Checking for available update...
[2024-06-24 00:52:55] Downloading manifest: https://cdn.steamstatic.com/client/steam_client_ubuntu12
[2024-06-24 00:52:55] Manifest download: send request
[2024-06-24 00:52:56] Manifest download: waiting for download to finish
[2024-06-24 00:52:56] Manifest download: finished
[2024-06-24 00:52:56] Downloaded new manifest: /client/steam_client_ubuntu12 version 1718904662, installed version 0, existing pending version 0
[2024-06-24 00:52:56] Package file tenfoot_images_all.zip.vz.193cb8c4eb4446698ea2c0a9e8c4e6b6a623dac7_5572671 missing or incorrect size
[2024-06-24 00:52:56] Package file steamui_websrc_all.zip.vz.9825bbd7bc1c4b28518b64b9fe3027eb92dccb8a_28120289 missing or incorrect size
[2024-06-24 00:52:56] Package file resources_misc_all.zip.vz.e86a975545f3ab21a77373870cb311ef93934b8c_2224876 missing or incorrect size
[2024-06-24 00:52:56] Package file resources_hidpi_all.zip.vz.3de815c3117712cb9eeb7ea4c8b275faf481dcfd_56342 missing or incorrect size
[2024-06-24 00:52:56] Package file resources_all.zip.vz.3c8b3203e5c69d75ea0684c2409b86fe4d0d6f83_2856188 missing or incorrect size
[2024-06-24 00:52:56] Package file strings_en_all.zip.8ebfe5f184cbfe30df39a3dde48e35ccbe8f2da9 missing or incorrect size
[2024-06-24 00:52:56] Package file strings_all.zip.vz.3b383251b8bf5cca5bd408c9d2864bc078e6d5b2_1993958 missing or incorrect size
[2024-06-24 00:52:56] Package file public_all.zip.vz.aa9ecccb35e9a29e3145d96f63e00eb525aa9b93_23521009 missing or incorrect size
[2024-06-24 00:52:56] Package file steamui_websrc_sounds_all.zip.vz.a2b25775b33d943e54c45d176558de379111ef5f_3220470 missing or incorrect size
[2024-06-24 00:52:56] Package file steamui_websrc_movies_all.zip.4d2183b0476852dfb695b8d70192a0ccece8c7d0 missing or incorrect size
[2024-06-24 00:52:56] Package file bins_ubuntu12.zip.vz.6a4ad992542188fa94c83da33e3f90829ba5ff4e_29141792 missing or incorrect size
[2024-06-24 00:52:56] Package file bins_sdk_ubuntu12.zip.vz.6ae839ae13bb1bb9d79b324b5dfe419facb54985_19548529 missing or incorrect size
[2024-06-24 00:52:56] Package file bins_codecs_ubuntu12.zip.vz.6592f3734983aaf25efdad3db98c8428a0dd6c1a_8752219 missing or incorrect size
[2024-06-24 00:52:56] Package file bins_misc_ubuntu12.zip.vz.4ec7cfd5b7753c8a06ba7a8338390d46c499de90_18659517 missing or incorrect size
[2024-06-24 00:52:56] Package file webkit_ubuntu12.zip.vz.dd14e17f61608201a3bfb69b33216ab2c1acafab_79885839 missing or incorrect size
[2024-06-24 00:52:56] Package file miles_ubuntu12.zip.vz.5093ef941e6e5195a60ab3259077694dec994016_295496 missing or incorrect size
[2024-06-24 00:52:56] Package file sdl3_ubuntu12.zip.vz.5bd5d54163989150c6eb9c48a11998a2731de647_6348077 missing or incorrect size
[2024-06-24 00:52:56] Package file steam_ubuntu12.zip.vz.1aaecdd79b765ac0bf70917979b37277b1b7dd5d_2615856 missing or incorrect size
[2024-06-24 00:52:56] Package file runtime_scout_ubuntu12.zip.06b1391e81cd5a855cfe38064fec799e76c7a678 missing or incorrect size
[2024-06-24 00:52:56] Package file runtime_sniper_ubuntu12.zip.cd8665cc23cd5ef8e5cbb1e2a5915d83529cdf30 missing or incorrect size
[2024-06-24 00:52:56] Add pending download: https://cdn.steamstatic.com/client/tenfoot_images_all.zip.vz.193cb8c4eb4446698ea2c0a9e8c4e6b6a623dac7_5572671
[2024-06-24 00:52:56] Manifest download: send request
[2024-06-24 00:52:56] Add pending download: https://cdn.steamstatic.com/client/steamui_websrc_all.zip.vz.9825bbd7bc1c4b28518b64b9fe3027eb92dccb8a_28120289
[2024-06-24 00:52:56] Manifest download: send request
[2024-06-24 00:52:56] Add pending download: https://cdn.steamstatic.com/client/resources_misc_all.zip.vz.e86a975545f3ab21a77373870cb311ef93934b8c_2224876
[2024-06-24 00:52:56] Manifest download: send request
[2024-06-24 00:52:56] Add pending download: https://cdn.steamstatic.com/client/resources_hidpi_all.zip.vz.3de815c3117712cb9eeb7ea4c8b275faf481dcfd_56342
[2024-06-24 00:52:56] Manifest download: send request
[2024-06-24 00:52:56] Add pending download: https://cdn.steamstatic.com/client/resources_all.zip.vz.3c8b3203e5c69d75ea0684c2409b86fe4d0d6f83_2856188
[2024-06-24 00:52:56] Manifest download: send request
[2024-06-24 00:52:56] Add pending download: https://cdn.steamstatic.com/client/strings_en_all.zip.8ebfe5f184cbfe30df39a3dde48e35ccbe8f2da9
[2024-06-24 00:52:56] Manifest download: send request
[2024-06-24 00:52:56] Add pending download: https://cdn.steamstatic.com/client/strings_all.zip.vz.3b383251b8bf5cca5bd408c9d2864bc078e6d5b2_1993958
[2024-06-24 00:52:56] Manifest download: send request
[2024-06-24 00:52:56] Add pending download: https://cdn.steamstatic.com/client/public_all.zip.vz.aa9ecccb35e9a29e3145d96f63e00eb525aa9b93_23521009
[2024-06-24 00:52:56] Manifest download: send request
[2024-06-24 00:52:56] Add pending download: https://cdn.steamstatic.com/client/steamui_websrc_sounds_all.zip.vz.a2b25775b33d943e54c45d176558de379111ef5f_3220470
[2024-06-24 00:52:56] Manifest download: send request
[2024-06-24 00:52:56] Add pending download: https://cdn.steamstatic.com/client/steamui_websrc_movies_all.zip.4d2183b0476852dfb695b8d70192a0ccece8c7d0
[2024-06-24 00:52:56] Manifest download: send request
[2024-06-24 00:52:56] Add pending download: https://cdn.steamstatic.com/client/bins_ubuntu12.zip.vz.6a4ad992542188fa94c83da33e3f90829ba5ff4e_29141792
[2024-06-24 00:52:56] Manifest download: send request
[2024-06-24 00:52:56] Add pending download: https://cdn.steamstatic.com/client/bins_sdk_ubuntu12.zip.vz.6ae839ae13bb1bb9d79b324b5dfe419facb54985_19548529
[2024-06-24 00:52:56] Manifest download: send request
[2024-06-24 00:52:56] Add pending download: https://cdn.steamstatic.com/client/bins_codecs_ubuntu12.zip.vz.6592f3734983aaf25efdad3db98c8428a0dd6c1a_8752219
[2024-06-24 00:52:56] Manifest download: send request
[2024-06-24 00:52:56] Add pending download: https://cdn.steamstatic.com/client/bins_misc_ubuntu12.zip.vz.4ec7cfd5b7753c8a06ba7a8338390d46c499de90_18659517
[2024-06-24 00:52:56] Manifest download: send request
[2024-06-24 00:52:56] Add pending download: https://cdn.steamstatic.com/client/webkit_ubuntu12.zip.vz.dd14e17f61608201a3bfb69b33216ab2c1acafab_79885839
[2024-06-24 00:52:56] Manifest download: send request
[2024-06-24 00:52:56] Add pending download: https://cdn.steamstatic.com/client/miles_ubuntu12.zip.vz.5093ef941e6e5195a60ab3259077694dec994016_295496
[2024-06-24 00:52:56] Manifest download: send request
[2024-06-24 00:52:56] Add pending download: https://cdn.steamstatic.com/client/sdl3_ubuntu12.zip.vz.5bd5d54163989150c6eb9c48a11998a2731de647_6348077
[2024-06-24 00:52:57] Manifest download: send request
[2024-06-24 00:52:57] Add pending download: https://cdn.steamstatic.com/client/steam_ubuntu12.zip.vz.1aaecdd79b765ac0bf70917979b37277b1b7dd5d_2615856
[2024-06-24 00:52:57] Manifest download: send request
[2024-06-24 00:52:57] Add pending download: https://cdn.steamstatic.com/client/runtime_scout_ubuntu12.zip.06b1391e81cd5a855cfe38064fec799e76c7a678
[2024-06-24 00:52:57] Manifest download: send request
[2024-06-24 00:52:57] Add pending download: https://cdn.steamstatic.com/client/runtime_sniper_ubuntu12.zip.cd8665cc23cd5ef8e5cbb1e2a5915d83529cdf30
[2024-06-24 00:52:57] Manifest download: send request
[2024-06-24 00:52:57] Downloading update (0 of 460,858 KB)...
[2024-06-24 00:53:01] Downloading update (5,442 of 460,858 KB)...
[2024-06-24 00:53:02] Downloading update (5,497 of 460,858 KB)...
[2024-06-24 00:53:07] Downloading update (11,309 of 460,858 KB)...
[2024-06-24 00:53:07] Downloading update (14,099 of 460,858 KB)...
[2024-06-24 00:53:24] Downloading update (34,308 of 460,858 KB)...
[2024-06-24 00:53:26] Downloading update (35,747 of 460,858 KB)...
[2024-06-24 00:53:28] Downloading update (37,920 of 460,858 KB)...
[2024-06-24 00:53:28] Downloading update (38,031 of 460,858 KB)...
[2024-06-24 00:53:29] Downloading update (39,978 of 460,858 KB)...
[2024-06-24 00:53:31] Downloading update (43,123 of 460,858 KB)...
[2024-06-24 00:53:39] Downloading update (55,775 of 460,858 KB)...
[2024-06-24 00:53:48] Downloading update (66,092 of 460,858 KB)...
[2024-06-24 00:54:00] Downloading update (87,759 of 460,858 KB)...
[2024-06-24 00:54:00] Downloading update (95,105 of 460,858 KB)...
[2024-06-24 00:54:06] Downloading update (101,897 of 460,858 KB)...
[2024-06-24 00:54:12] Downloading update (114,180 of 460,858 KB)...
[2024-06-24 00:54:12] Downloading update (119,426 of 460,858 KB)...
[2024-06-24 00:54:18] Downloading update (126,234 of 460,858 KB)...
[2024-06-24 00:54:19] Downloading update (137,501 of 460,858 KB)...
[2024-06-24 00:54:28] Downloading update (147,757 of 460,858 KB)...
[2024-06-24 00:54:29] Downloading update (152,912 of 460,858 KB)...
[2024-06-24 00:55:06] Downloading update (196,553 of 460,858 KB)...
[2024-06-24 00:55:39] Downloading update (232,258 of 460,858 KB)...
[2024-06-24 00:55:50] Downloading update (237,717 of 460,858 KB)...
[2024-06-24 00:55:50] Downloading update (240,272 of 460,858 KB)...
[2024-06-24 00:56:05] Downloading update (260,945 of 460,858 KB)...
[2024-06-24 00:56:09] Downloading update (281,564 of 460,858 KB)...
[2024-06-24 00:57:09] Error: Download of package (runtime_scout_ubuntu12) failed after 0 bytes (0 : 200).
[2024-06-24 00:57:09] Downloading update (255,486 of 460,858 KB)...
[2024-06-24 00:57:18] Error: Download of package (runtime_sniper_ubuntu12) failed after 0 bytes (0 : 200).
[2024-06-24 00:57:18] Downloading update (234,813 of 460,858 KB)...
[2024-06-24 00:57:18] Package file runtime_scout_ubuntu12.zip.06b1391e81cd5a855cfe38064fec799e76c7a678 missing or incorrect size
[2024-06-24 00:57:18] Package file runtime_sniper_ubuntu12.zip.cd8665cc23cd5ef8e5cbb1e2a5915d83529cdf30 missing or incorrect size
[2024-06-24 00:57:18] Add pending download: https://cdn.steamstatic.com/client/runtime_scout_ubuntu12.zip.06b1391e81cd5a855cfe38064fec799e76c7a678
[2024-06-24 00:57:18] Manifest download: send request
[2024-06-24 00:57:18] Add pending download: https://cdn.steamstatic.com/client/runtime_sniper_ubuntu12.zip.cd8665cc23cd5ef8e5cbb1e2a5915d83529cdf30
[2024-06-24 00:57:18] Manifest download: send request
[2024-06-24 00:58:00] Error: Download of package (runtime_sniper_ubuntu12) failed after 0 bytes (0 : 0).
[2024-06-24 00:58:00] Error: Download of package (runtime_scout_ubuntu12) failed after 0 bytes (0 : 0).
[2024-06-24 00:58:00] Exhausted list of download hosts
[2024-06-24 00:58:00] Repeatedly failed to download packages, giving up
[2024-06-24 00:58:00] Saving metrics to disk (/home/adrian/.local/share/Steam/package/steam_client_metrics.bin)
[2024-06-24 00:58:00] Error: Steam needs to be online to update.	 Please confirm your network connection and try again.
[2024-06-24 01:12:57] Shutdown
CWorkThreadPool::~CWorkThreadPool: work complete queue not empty, 5 items discarded.
src/tier0/threadtools.cpp (3706) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x64849eb0/0x0xe96e81'
src/tier0/threadtools.cpp (3706) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x64849eb0/0x0xe96e81'
```

When I run steam from the terminal again this is what shows and it gives the same error (fail to download runtime_sniper_ubuntu12):
```~ $ steam
steam.sh[9767]: Running Steam on debian 12 64-bit
steam.sh[9767]: STEAM_RUNTIME is enabled by the user
setup.sh[9831]: Steam runtime environment up-to-date!
/home/adrian/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: linje 85: fant ikke kommando steam-runtime-identify-library-abi
run.sh[9843]: steam-runtime-identify-library-abi --ldconfig-paths failed, falling back to ldconfig
steam.sh[9767]: Can't find 'steam-runtime-check-requirements', continuing anyway
Debug level is 1
Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA PageSize:4096 Running on Cortex-A72 with 4 Cores
Params database has 31 entries
Box86 with Dynarec v0.3.7 fc0b51f3 built on Jun 19 2024 23:33:09
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/:i686/
Using default BOX86_PATH: ./:bin/
Counted 67 Env var
Looking for /home/adrian/.local/share/Steam/ubuntu12_32/steam
steam detected
Apply RC params for steam
Applying BOX86_NOGTK=1
Applying BOX86_DYNAREC_STRONGMEM=1
Applying BOX86_DYNAREC_CALLRET=0
Applying BOX86_EMULATED_LIBS=libudev.so.0:libSDL2-2.0.so.0
argv[1]="-no-cef-sandbox"
argv[2]="steam://open/minigameslist"
Rename process to "steam"
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Using native(wrapped) libX11.so.6
Using native(wrapped) libm.so.6
[2024-06-24 01:17:50] Startup - updater built Jan 13 2024 00:51:43
[2024-06-24 01:17:50] Startup - Steam Client launched with: '/home/adrian/.local/share/Steam/ubuntu12_32/steam' '-no-cef-sandbox' 'steam://open/minigameslist'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
Using native(wrapped) crashhandler.so
Using native(wrapped) libGL.so.1
[2024-06-24 01:17:51] Loading cached metrics from disk (/home/adrian/.local/share/Steam/package/steam_client_metrics.bin)
[2024-06-24 01:17:51] Failed to load cached hosts file (File 'update_hosts_cached.vdf' not found), using defaults
[2024-06-24 01:17:51] Using the following download hosts for Public, Realm steamglobal
[2024-06-24 01:17:51] 1. https://cdn.steamstatic.com, /client/, Realm 'steamglobal', weight was 1, source = 'baked in'
[2024-06-24 01:17:51] Verifying installation...
[2024-06-24 01:17:51] Unable to read and verify install manifest /home/adrian/.local/share/Steam/package/steam_client_ubuntu12.installed
[2024-06-24 01:17:51] Verification complete
[2024-06-24 01:17:51] Downloading Update...
[2024-06-24 01:17:51] Checking for available update...
[2024-06-24 01:17:51] Downloading manifest: https://cdn.steamstatic.com/client/steam_client_ubuntu12
[2024-06-24 01:17:51] Manifest download: send request
[2024-06-24 01:17:51] Manifest download: waiting for download to finish
[2024-06-24 01:17:52] Manifest download: finished
[2024-06-24 01:17:52] Downloaded new manifest: /client/steam_client_ubuntu12 version 1718904662, installed version 0, existing pending version 0
[2024-06-24 01:17:52] Package file runtime_scout_ubuntu12.zip.06b1391e81cd5a855cfe38064fec799e76c7a678 missing or incorrect size
[2024-06-24 01:17:52] Package file runtime_sniper_ubuntu12.zip.cd8665cc23cd5ef8e5cbb1e2a5915d83529cdf30 missing or incorrect size
[2024-06-24 01:17:52] Add pending download: https://cdn.steamstatic.com/client/runtime_scout_ubuntu12.zip.06b1391e81cd5a855cfe38064fec799e76c7a678
[2024-06-24 01:17:52] Manifest download: send request
[2024-06-24 01:17:52] Add pending download: https://cdn.steamstatic.com/client/runtime_sniper_ubuntu12.zip.cd8665cc23cd5ef8e5cbb1e2a5915d83529cdf30
[2024-06-24 01:17:52] Manifest download: send request
[2024-06-24 01:17:52] Downloading update (0 of 226,045 KB)...
[2024-06-24 01:18:02] Downloading update (10,497 of 226,045 KB)...
[2024-06-24 01:18:14] Error: Download of package (runtime_sniper_ubuntu12) failed after 0 bytes (0 : 0).
[2024-06-24 01:18:52] Downloading update (58,148 of 226,045 KB)...
[2024-06-24 01:18:55] Downloading update (61,488 of 226,045 KB)...
[2024-06-24 01:19:00] Package file runtime_sniper_ubuntu12.zip.cd8665cc23cd5ef8e5cbb1e2a5915d83529cdf30 missing or incorrect size
[2024-06-24 01:19:00] Add pending download: https://cdn.steamstatic.com/client/runtime_sniper_ubuntu12.zip.cd8665cc23cd5ef8e5cbb1e2a5915d83529cdf30
[2024-06-24 01:19:00] Manifest download: send request
[2024-06-24 01:19:01] Downloading update (61,490 of 226,045 KB)...
[2024-06-24 01:19:01] Downloading update (61,522 of 226,045 KB)...
[2024-06-24 01:19:01] Downloading update (61,618 of 226,045 KB)...
[2024-06-24 01:19:01] Downloading update (61,670 of 226,045 KB)...
[2024-06-24 01:19:16] Downloading update (78,308 of 226,045 KB)...
[2024-06-24 01:20:24] Downloading update (140,676 of 226,045 KB)...
[2024-06-24 01:21:24] Error: Download of package (runtime_sniper_ubuntu12) failed after 0 bytes (0 : 200).
[2024-06-24 01:21:24] Downloading update (61,488 of 226,045 KB)...
[2024-06-24 01:21:24] Exhausted list of download hosts
[2024-06-24 01:21:24] Repeatedly failed to download packages, giving up
[2024-06-24 01:21:24] Saving metrics to disk (/home/adrian/.local/share/Steam/package/steam_client_metrics.bin)
[2024-06-24 01:21:24] Error: Steam needs to be online to update.	 Please confirm your network connection and try again.
[2024-06-24 01:40:11] Shutdown
CWorkThreadPool::~CWorkThreadPool: work complete queue not empty, 1 items discarded.
src/tier0/threadtools.cpp (3706) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x6563d320/0x0xe9eff1'
src/tier0/threadtools.cpp (3706) : Assertion Failed: Illegal termination of worker thread 'Thread(0x0x6563d320/0x0xe9eff1'```

**Comment by Botspot** [comment] 2024-07-02 17:34
This issue is now solved. Please update Pi-Apps.

**Comment by ptitSeb** [comment] 2024-07-02 17:38
also, duplicate of #1612

**Closed by ptitSeb** 2024-07-02 17:38 UTC
