### ISSUE TITLE
Intel Quartus Prime not working on m1

### ISSUE THREAD

**Issue by JoelSerranoLozano** [ptitSeb/box64#422] opened 2022-10-09 23:12 UTC
I recently installed asahi linux on my mac, I tough using linux would make it compatible with intel quartus, which I need for my studies, so I installed box64 and ran it, but gave me the following error I ran the program with x86-64 bash mode.

[intelquartuserror.txt](https://github.com/ptitSeb/box64/files/9742735/intelquartuserror.txt)

I'm new at linux and I don't know where to start with this problem thank you for advance and keep up this amazing project!

**Comment by ptitSeb** [comment] 2022-10-10 06:11
This is a duplicate of #360

**Comment by JoelSerranoLozano** [comment] 2022-10-10 09:44
Thanks Will check it out

**Comment by JoelSerranoLozano** [comment] 2022-10-10 15:36
for me it is not working I think is not exactly the same I have the following error:
`Error: Global Symbol qt_version_tag not found, cannot apply R_X86_64_GLOB_DAT @0xfffeca5e4290 ((nil)) in /home/oriols/intelFPGA_lite/21.1/quartus/linux64/libsys_ictq.so
Error: Global Symbol qt_version_tag not found, cannot apply R_X86_64_GLOB_DAT @0xfffeca253940 ((nil)) in /home/oriols/intelFPGA_lite/21.1/quartus/linux64/libsys_qgq.so
Error: Global Symbol qt_version_tag not found, cannot apply R_X86_64_GLOB_DAT @0xfffeca229328 ((nil)) in /home/oriols/intelFPGA_lite/21.1/quartus/linux64/libmega_qsysipc.so
Error: Global Symbol qt_version_tag not found, cannot apply R_X86_64_GLOB_DAT @0xfffeca15b310 ((nil)) in /home/oriols/intelFPGA_lite/21.1/quartus/linux64/libsys_qui.so`

and
`Error initializing native libcrypt.so.1 (last dlerror is libcrypt.so.1: cannot open shared object file: No such file or directory)
Error loading needed lib libcrypt.so.1
Error loading one of needed lib
Error initializing needed lib libpython3.7m.so.1
Error loading one of needed lib
Error initializing needed lib libpython3.so
Error loading one of needed lib
Error initializing needed lib libcomp_rcomp.so
Error loading one of needed lib
Error: loading needed libs in elf /home/oriols/intelFPGA_lite/21.1/quartus/linux64/quartus
` thanks for advance

**Comment by JoelSerranoLozano** [comment] 2022-10-10 20:40
a little update I have installed missing libs and  it gave me a diferent error this time 
[OutPut.txt](https://github.com/ptitSeb/box64/files/9749138/OutPut.txt)

**Comment by JoelSerranoLozano** [comment] 2022-10-12 18:21
`2514|SIGSEGV @0x64981358 (???(/home/oriols/intelFPGA_lite/quartus/linux64/quartus+0x64981358)) (x64pc=0xfffed3
[output.txt](https://github.com/ptitSeb/box64/files/9767705/output.txt)
9db76b//home/oriols/intelFPGA_lite/quartus/linux64/libstdc++.so.6:"???", rsp=0xffff17ca7280, stack=0xffff174a8000:0xffff17ca8000 own=(nil) fp=0xfffedc775740), for accessing 0xfffffffffffffff8 (code=1/prot=0), db=(nil)((nil):(nil)/(nil):(nil)/???:clean, hash:0/0) handler=(nil)
RSP-0x20:0x0000000000000004 RSP-0x18:0x0000fffed3c4d646 RSP-0x10:0x0000000000000004 RSP-0x08:0x0000fffed39da549
RSP+0x00:0x0000fffedb842398 RSP+0x08:0x00000000833a28d0 RSP+0x10:0x0000ffff17ca72b0 RSP+0x18:0x0000fffedb83ff9b
`

that's what is showing me now

**Comment by YamashitaRen** [comment] 2022-10-20 16:18
Getting rougly the same error on a virtualized Debian.
`Using native(wrapped) libz.so.1
Using native(wrapped) liblzma.so.5
Using emulated /home/me/intelFPGA_lite/21.1/quartus/linux64/libicui18n.so.69
Using emulated /home/me/intelFPGA_lite/21.1/quartus/linux64/libboost_timer.so.1.59.0
Using emulated /home/me/intelFPGA_lite/21.1/quartus/linux64/libboost_chrono.so.1.59.0
1802|SIGSEGV @0xffff5c70b49c (???(0xffff5c70b49c)) (x64pc=0xffff75d28550//home/me/intelFPGA_lite/21.1/quartus/linux64/libccl_mem.so:"/home/me/intelFPGA_lite/21.1/quartus/linux64/libccl_mem.so/_Z24mem_register_dll_for_pgoPKcS0_ + 272", rsp=0xffff9638cd38, stack=0xffff95b8e000:0xffff9638e000 own=(nil) fp=0x100180de0), for accessing 0x2a0000004a (code=1/prot=0), db=0x9745b050(0xffff5c70b49c:0xffff5c70b6d8/0xffff75d28550:0xffff75d285ad//home/me/intelFPGA_lite/21.1/quartus/linux64/libccl_mem.so/_Z24mem_register_dll_for_pgoPKcS0_ + 272:clean, hash:8dad1db9/8dad1db9) handler=(nil)
RAX:0x0000ffff9638cda0 RCX:0x0000000100180df8 RDX:0x0000000100178490 RBX:0x0000002a0000002a 
RSP:0x0000ffff9638cd38 RBP:0x0000ffff9638cde8 RSI:0x0000ffff96fd7700 RDI:0x0000000100180df8 
 R8:0x00000001001bf000  R9:0x0000020000000000 R10:0x00000001001bf000 R11:0x00000001001bf000 
R12:0x0000000000000004 R13:0x0000ffff9638cd98 R14:0x0000000000000000 R15:0x00000001001d9270 
RSP-0x20:0x0000ffff92172680 RSP-0x18:0x0000ffff9638cde8 RSP-0x10:0x0000000000000000 RSP-0x08:0x0000ffff75d284a1
RSP+0x00:0x0000000000000000 RSP+0x08:0x00000001001d9278 RSP+0x10:0x00000001001d9270 RSP+0x18:0x0000ffff95197ee0
Erreur de segmentation
`

**Comment by ptitSeb** [comment] 2022-10-20 16:39
Yeah, I reproduce some issue also on my side. Still working on some box64 refactor that might help. I'll keep an eye on Quartus while I continue the next refactors.

**Comment by ptitSeb** [comment] 2022-12-04 20:35
It should work now with latest box64. Can you update and try again?

**Comment by Pedroo64** [comment] 2022-12-14 22:00
Hi,

I've been trying to launch Quartus on MacBook M1 Pro using lima-vm. I've managed to install Quartus without no problem. When I launch Quartus I get the following error.

[quartus.output.txt](https://github.com/ptitSeb/box64/files/10231938/quartus.output.txt)

Don't know what causes the crash...

I've tried also to run Quartus on docker by passing the parameter "--platform=linux/amd64" to run a docker container on a x64. Quartus runs but synthesis step loops for ever...

I mention this because I'dont know if it's a missing library or something else...

Thank you!

Pedro

**Comment by space192** [comment] 2023-01-10 13:24
hey ! So I ran the software it starts ! but crashes after 5 seconds x)
here is the output when I launch the program on M1 mac in parallels VM ubuntu 20.04 arm64:
[output.txt](https://github.com/ptitSeb/box64/files/10383083/output.txt)

**Comment by space192** [comment] 2023-03-16 19:52
Hey so I tried once again with the last version you published, i'm on asahi linux now !
here is the output from when I launch the program 
[output.txt](https://github.com/ptitSeb/box64/files/10995320/output.txt)

once again thanks for the amazing work !

**Comment by ptitSeb** [comment] 2023-11-15 14:25
Hi, I think it's fixed now. Can you update and try again?

**Comment by space192** [comment] 2023-12-21 10:43
Hey, sorry for the delay, I get the following output:
[output.txt](https://github.com/ptitSeb/box64/files/13740376/output.txt)
you can see that there's an error on `libjpeg.so.62`
I checked and on my Asahi fedora 39 I have the file located at /lib64/libjpeg.so.62
If you have any idea I can try them out :D

**Comment by ptitSeb** [comment] 2024-02-15 17:16
I have made some major changes in elfloader. quartus_pgmw might work (at least the 21.1 version), but the 16K pagesize on the M1 might makes things more complicated.
Anyway, if you can update and try again.

**Comment by LukeShortCloud** [comment] 2024-11-02 17:52
This should be fixed now. Closing as resolved.

**Closed by LukeShortCloud** 2024-11-02 17:52 UTC
