### ISSUE TITLE
Caves of Qud Linux64 error

### ISSUE THREAD

**Issue by alvinhanaji** [ptitSeb/box64#130] opened 2021-10-11 09:55 UTC
Tried to get Caves of Qud linux to work, it's a Unity game so this may or may not be box64 related but figured I'd ask here anyway

Using emulated /home/cpi/Games/coqbeta/CoQ_Data/MonoBleedingEdge/x86_64/libmonobdwgc-2.0.so
Mono path[0] = '/home/cpi/Games/coqbeta/CoQ_Data/Managed'
Mono config path = '/home/cpi/Games/coqbeta/CoQ_Data/MonoBleedingEdge/etc'
0x82953ac0: Stack is corrupted, aborting
==== CPU Registers ====
RAX=b94ce4608b790004 RCX=0000000000000000 RDX=0000ffff826f6310 RBX=0000ffff826f6280 RSP=0000ffff826f6268 FLAGS=--S--PC
RBP=0000ffff826f6318 RSI=0000ffff826f6318 RDI=0000ffff826f6280  R8=0000000000000001  R9=0000000000000010 
R10=0000fffebdafe548 R11=0000fffebdafe548 R12=0000ffff826f6310 R13=0000ffff7ff41a89 R14=0000ffff826f6368 
R15=0000ffff00000130 RIP=0000000082953093 
======== Stack ========
Stack is from FFFF826F6318 to FFFF826F6268
Old IP: 82953AC0
Stop waiting for remaining thread 5635
5635|0x82943003: Unimplemented Opcode (94) 82 00 00 00 00 F0 CF 93 82 00 00 00 00 00 00
5635|0x82943003: Unimplemented Opcode (94) 82 00 00 00 00 F0 CF 93 82 00 00 00 00 00 00
5635|0x82943003: Unimplemented Opcode (94) 82 00 00 00 00 F0 CF 93 82 00 00 00 00 00 00
5635|0x82943003: Unimplemented Opcode (94) 82 00 00 00 00 F0 CF 93 82 00 00 00 00 00 00
5635|0x82943003: Unimplemented Opcode (94) 82 00 00 00 00 F0 CF 93 82 00 00 00 00 00 00

from the Player.log, the actual output logging is really huge and is just lotta errors, might be mono related

**Comment by alvinhanaji** [comment] 2021-10-14 02:17
> Could you please run
> 
> ```shell
> strings /home/cpi/Games/coqbeta/CoQ_Data/resources.assets | grep "20[0-9][0-9]\."
> ```
> 
> and show the output?
> 
> This will return the Unity version used to compile the game and might give some more insight into what's happening.

The Unity version is 2020.3.19f1

**Comment by mogery** [comment] 2021-10-14 05:38
> The Unity version is 2020.3.19f1

Alright, thanks.
I don't have access to QoD executables, but I can try to build a dummy Unity project with the same version to (hopefully) exhibit the same crash.

**Comment by mogery** [comment] 2021-10-14 05:45
Also, this is a longshot, but could you try to run the game again with a fresh pull? My fix for a Unity issue just got merged, and it might affect this game too.

**Comment by alvinhanaji** [comment] 2021-10-14 08:43
Just did a fresh pull, rebuild, and tried it again. Unfortunately the same result.

**Comment by mogery** [comment] 2021-10-14 10:48
Thought so, but worth a try. I'll get to debugging when I get home.

**Comment by alvinhanaji** [comment] 2021-10-14 23:24
Sent via itch.io, thanks for the response and good luck! Worst case it's a rad game.

**Comment by mogery** [comment] 2021-10-15 12:56
Hey there.

I can't recreate this at all. The game runs just fine for me. What hardware are you trying to run this on?
Are you running the beta version of the game or the default?
Could you try running it with the following command?
```
MESA_GL_VERSION_OVERRIDE=3.2 ./CoQ.x86_64 -force-glcore32 -screen-fullscreen 0 -screen-width 1280 -screen-height 720
```

**Comment by alvinhanaji** [comment] 2021-10-17 08:11
I'm running this game on  a DevTerm with an A06 module which is an RK3399. Unfortunately the game still doesn't run with that command. I have attached a Player.log with LOG 3 here if it can help
[Player.log](https://github.com/ptitSeb/box64/files/7359427/Player.log)
.

**Comment by mogery** [comment] 2021-10-17 09:44
> Is this while the game is running? Problem I can't get the game to start or run at all. Do I run cat /proc/$(pgrep CoQ)/maps after it's finished or while it's attempting?

While it's attempting. Ideally you should run it after you see `Mono config path = ...` in Player.log.

**Comment by alvinhanaji** [comment] 2021-10-17 09:50
Here is the player.log
[Player.log](https://github.com/ptitSeb/box64/files/7359567/Player.log)

**Comment by alvinhanaji** [comment] 2021-10-17 09:52
Here is also the mem map, let me know if I didn't run it at the correct time
[memmap.txt](https://github.com/ptitSeb/box64/files/7359573/memmap.txt)

**Comment by alvinhanaji** [comment] 2021-10-17 09:59
I appreciate the help! I think I got the rest of the memmap here.
[memmap.txt](https://github.com/ptitSeb/box64/files/7359596/memmap.txt)

**Comment by alvinhanaji** [comment] 2021-10-17 10:01
Actually here's also another latest one as well with the latest Player.log
[Player.log](https://github.com/ptitSeb/box64/files/7359599/Player.log)
[memmap.txt](https://github.com/ptitSeb/box64/files/7359600/memmap.txt)

**Comment by mogery** [comment] 2021-10-17 10:02
> Actually here's also another latest one as well with the latest Player.log [Player.log](https://github.com/ptitSeb/box64/files/7359599/Player.log) [memmap.txt](https://github.com/ptitSeb/box64/files/7359600/memmap.txt)

Perfect! Thank you.

**Comment by mogery** [comment] 2021-10-17 11:05
@alvinhanaji This still feels like it should be recreatable. What OS are you running, with version? Could you send me a `neofetch` output?

**Comment by mogery** [comment] 2021-10-17 16:50
Bingo! Fails on hirsute, same error message. Investigating...

**Comment by mogery** [comment] 2021-10-17 19:28
@alvinhanaji I seem to have fixed the issue by adding an alignment wrapper to `pthread_getattr_np`. It works on my side, but please test it on yours by cloning my branch of box64 like this:

```bash
git clone https://github.com/mogery/box64
cd box64
git checkout getattr-align-wrap
```

...and following the normal build instructions.

**Comment by ptitSeb** [comment] 2021-10-17 19:41
Ah yes, indeed, I forgot to wrap `pthread_getattr_np`

**Comment by alvinhanaji** [comment] 2021-10-18 00:38
With less logging but just as big. [Player.log](https://github.com/ptitSeb/box64/files/7361157/Player.log)

**Comment by alvinhanaji** [comment] 2021-10-18 00:45
not sue if it'll help but here is also the version of mono I am running, is there something I have to update?

cpi@clockworkpi-a06:~/Games/cavesofqud-linux-beta$ mono --version
Mono JIT compiler version 6.8.0.105 (Debian 6.8.0.105+dfsg-3 Mon Apr 27 19:45:06 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       normal
	Notifications: epoll
	Architecture:  arm64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       preemptive
	GC:            sgen (concurrent by default)

**Comment by mogery** [comment] 2021-10-18 04:43
> Thanks! It seems to try to run past that initial error now but unfortunately it seems to be a new issue where it hangs now and spams the log.
> 
> [Player.log](https://github.com/ptitSeb/box64/files/7361145/Player.log)
> 
> .

This is actually "normal"! The game should start after waiting roughly 2 minutes. For some reason, Unity preload is quite slow on box64. I'm currently searching for the cause.

**Comment by alvinhanaji** [comment] 2021-10-18 06:29
Unfortunately even after letting it run for a full 30 minutes it still doesn't move. The window does open for windowed mode but nothing happens.

**Comment by mogery** [comment] 2021-10-18 08:07
> Unfortunately even after letting it run for a full 30 minutes it still doesn't move. The window does open for windowed mode but nothing happens.

Well that's odd. What parameters are you running with?

**Closed as completed** 2021-10-18 08:12 UTC
