### ISSUE TITLE
Steam does not open when runing ubuntu noble (Linux 4 switch)

### ISSUE THREAD

**Issue by Awesomeangotti** [ptitSeb/box64#2023] opened 2024-11-13 02:41 UTC
The folks at the linux 4 switch discord said to post the terminal output here.

VIRGL Server Started
steam.sh[14873]: Running Steam on ubuntu 24.04 64-bit
steam.sh[14873]: STEAM_RUNTIME is enabled by the user
setup.sh[14938]: Steam runtime environment up-to-date!
/home/awesome/.local/share/Steam/ubuntu12_32/steam-runtime/run.sh: line 85: steam-runtime-identify-library-abi: command not found
run.sh[14950]: steam-runtime-identify-library-abi --ldconfig-paths failed, falling back to ldconfig
steam.sh[14873]: Couldn't find /home/awesome/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/srt-logger, logging to console-linux.txt
steam.sh[14873]: Can't find 'steam-runtime-check-requirements', continuing anyway
Debug level is 1
Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA AES PMULL PageSize:4096 Running on Cortex-A57 with 4 Cores
Params database has 32 entries
Box86 with Dynarec v0.3.7 1e749beb built on Nov 10 2024 06:39:36
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/:i686/
Using default BOX86_PATH: ./:bin/
Counted 87 Env var
BOX86 try to Preload libgtk3-nocsd.so.0 
Looking for /home/awesome/.local/share/Steam/ubuntu12_32/steam
steam detected
Apply RC params for steam
Applying BOX86_NOGTK=1
Applying BOX86_DYNAREC_STRONGMEM=1
Applying BOX86_DYNAREC_CALLRET=0
Applying BOX86_EMULATED_LIBS=libudev.so.0:libSDL2-2.0.so.0
argv[1]="-no-cef-sandbox"
Rename process to "steam"
Error loading needed lib libgtk3-nocsd.so.0
Warning, cannot pre-load libgtk3-nocsd.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
Using native(wrapped) libX11.so.6
Using native(wrapped) libm.so.6
[2024-11-12 21:38:27] Startup - updater built Jul 16 2024 23:21:18
[2024-11-12 21:38:27] Startup - Steam Client launched with: '/home/awesome/.local/share/Steam/ubuntu12_32/steam' '-no-cef-sandbox'
ILocalize::AddFile() failed to load file "public/steambootstrapper_english.txt".
src/steamexe/updateui_xwin.cpp (1466) : BFileExists( m_FontFileRegular )
src/steamexe/updateui_xwin.cpp (1466) : BFileExists( m_FontFileRegular )
Using emulated /home/awesome/.local/share/Steam/ubuntu12_32/crashhandler.so
Warning: Weak Symbol _ZGTtnaj not found, cannot apply R_386_JMP_SLOT 0x6009aac0 (0x81b6)
11/12 21:38:27 minidumps folder is set to /tmp/dumps
11/12 21:38:27 Init: Installing breakpad exception handler for appid(steam)/version(1.0)/tid(14978)
Debug level is 1
Dynarec for ARMv8, with extension: HALF FAST_MULT EDSP NEON VFPv4 IDIVA AES PMULL PageSize:4096 Running on Cortex-A57 with 4 Cores
Params database has 32 entries
Box86 with Dynarec v0.3.7 1e749beb built on Nov 10 2024 06:39:36
Using default BOX86_LD_LIBRARY_PATH: ./:lib/:lib32/:x86/:i686/
Using default BOX86_PATH: ./:bin/
Counted 88 Env var
BOX86 try to Preload libgtk3-nocsd.so.0 
Looking for /home/awesome/.local/share/Steam/linux32/steamerrorreporter
steam detected
argv[1]="uptime"
argv[2]="84"
argv[3]="StartupTime"
argv[4]="1731466047"
argv[5]="CrashTime"
argv[6]="1731466132"
argv[7]="BuildID"
argv[8]="20240716232046"
argv[9]="Platform"
argv[10]="Linux"
argv[11]="ProductName"
argv[12]="steam"
argv[13]="SteamUniverse"
argv[14]="Public"
argv[15]="URL"
argv[16]="www.steampowered.com"
argv[17]="Vendor"
argv[18]="Valve"
argv[19]="Version"
argv[20]="1.0"
Rename process to "steamerrorreporter"
Error loading needed lib libgtk3-nocsd.so.0
Warning, cannot pre-load libgtk3-nocsd.so.0
Using native(wrapped) libdl.so.2
Using native(wrapped) libc.so.6
Using native(wrapped) ld-linux.so.2
Using native(wrapped) libpthread.so.0
Using native(wrapped) librt.so.1
Using native(wrapped) libbsd.so.0
local/share/Steam/linux32/steamerrorreporter[14989]: Uploading dump (out-of-process)
/tmp/dumps/assert_20241112213827_3.dmp
Error loading needed lib libcurl.so
Warning: Cannot dlopen("libcurl.so"/0x30017013, 2)
awesome@awesome-switch:~$ Using native(wrapped) libcurl.so.4
local/share/Steam/linux32/steamerrorreporter[14989]: Finished uploading minidump (out-of-process): success = yes
local/share/Steam/linux32/steamerrorreporter[14989]: response: CrashID=bp-c334c7c5-8a49-41cb-85ff-31b032241112
local/share/Steam/linux32/steamerrorreporter[14989]: file ''/tmp/dumps/assert_20241112213827_3.dmp'', upload yes: ''CrashID=bp-c334c7c5-8a49-41cb-85ff-31b032241112''

**Comment by ptitSeb** [comment] 2024-11-13 07:12
The folks at linux 4 switch discord should have looks there https://github.com/ptitSeb/box86/issues/1012 before creating a new ticket.

**Comment by CalcProgrammer1** [comment] 2024-11-13 17:40
I installed libcurl4:arm64 and :armhf on Debian to fix this.  Not sure about Ubuntu.

**Comment by theofficialgman** [comment] 2024-11-24 21:13
probably duplicate of https://github.com/ptitSeb/box64/issues/2046

**Comment by LukeShortCloud** [comment] 2024-12-21 15:07
The final solution for the possible duplicate GitHub Issue was to delete or move the `~/.local/share/Steam/ubuntu12_32/crashhandler.so` library file.

Let us know if that doesn't help.

Closing as resolved for now.

**Closed by LukeShortCloud** 2024-12-21 15:07 UTC
