### ISSUE TITLE
Failed to install genshin impact in Arch Linux with wow64 error, using Loongson 3A6000

### ISSUE THREAD

**Issue by 4Darmygeometry** [ptitSeb/box64#1464] opened 2024-04-25 13:07 UTC
<img width="960" alt="ARCHLINUX+genshin" src="https://github.com/ptitSeb/box64/assets/87938880/51fdb83b-d861-46c8-a091-b4929517cfe6">
![b85ee3d6b5e1c9fa76522ef544c5d0df191109672](https://github.com/ptitSeb/box64/assets/87938880/ddeca8db-6fc7-4d84-9eae-33b65a53f83c)
failed to load ntdll.dll

**Comment by 4Darmygeometry** [comment] 2024-04-25 13:13
![b85ee3d6b5e1c9fa76522ef544c5d0df191109672](https://github.com/ptitSeb/box64/assets/87938880/ddeca8db-6fc7-4d84-9eae-33b65a53f83c)

**Comment by ptitSeb** [comment] 2024-04-25 13:15
Longsoon use 16K pagesize, and box64 is not yet able to run wine with this.
It's on the TODO, but not in the immediate todo, so it will come later.

Duplicate of #1448 so closing this one, 1 ticket is enough.

**Closed by ptitSeb** 2024-04-25 13:15 UTC
