### ISSUE TITLE
AVX Instructions Required In Death Stranding 

### ISSUE THREAD

**Issue by sector-a** [ptitSeb/box64#1471] opened 2024-04-27 07:04 UTC
When will be AVX added to box64?
I saw an issue (july 2023) where you said that it will be added in the future, but it was like 9 months already and nothing
AVX support would be really useful.

**Comment by ptitSeb** [comment] 2024-04-27 08:08
I am aware of that.

AVX is still planed, but still no date. It's closer than 9 months ago, that's all I can say.

**Comment by ptitSeb** [comment] 2024-05-06 14:32
Keeping it open, it's not done yet, and to avoid further tickets.

**Comment by ptitSeb** [comment] 2024-06-06 17:21
Actually, there is AVX support now, and it works fine with Death Stranding.

Note that I couldn't run it on my X13s with Turnip, only on my Ampere with an NVidia graphic card.

**Comment by sector-a** [comment] 2024-06-06 17:24
Awesome!

**Comment by RichardMiller90** [comment] 2024-07-08 11:58
Please avx is not working with snapdragon 8 gen 3. I tried running death stranding nothing I'd working.

**Comment by rajdakin** [comment] 2024-07-08 12:03
1. Make sure you have the latest box64 version installed, the default got switched pretty recently and bug fixes are quite frequent.
2. If this doesn't solve the issue, what is the output? Please copy and paste it inside code blocks (surround the pasted output with *triple* backquotes, \`\`\` ...blablabla... \`\`\`).

**Comment by ptitSeb** [comment] 2024-07-08 12:25
> Please avx is not working with snapdragon 8 gen 3. I tried running death stranding nothing Is working.

The issue is the turnip freedreno driver that is missing some vulkan extension for this game. It runs fine on my side with an NVidia driver.

**Comment by RichardMiller90** [comment] 2024-07-08 13:12
> > Please avx is not working with snapdragon 8 gen 3. I tried running death stranding nothing Is working.
> 
> The issue is the turnip freedreno driver that is missing some vulkan extension for this game. It runs fine on my side with an NVidia driver.

Ok. So I should wait for turpin driver update to get the issues fixed. Thanks, good to know.

**Comment by ptitSeb** [comment] 2024-07-08 13:19
> > > Please avx is not working with snapdragon 8 gen 3. I tried running death stranding nothing Is working.
> > 
> > 
> > The issue is the turnip freedreno driver that is missing some vulkan extension for this game. It runs fine on my side with an NVidia driver.
> 
> Ok. So I should wait for turpin driver update to get the issues fixed. Thanks, good to know.

Note that I have no idea if someone is looking at this. I have not open a ticket on mesa about this on my side.

**Comment by LukeShortCloud** [comment] 2024-10-31 14:21
AVX is now supported in Box64. The last remaining issue is a Mesa driver issue in Turnip which it outside of our control. Closing as complete.

**Closed by LukeShortCloud** 2024-10-31 14:21 UTC
