### ISSUE TITLE
About unity game on l4t-ubuntu 18.04

### ISSUE THREAD

**Issue by ruje0504** [ptitSeb/box64#930] opened 2023-08-11 17:58 UTC
OS: L4T Ubuntu 18.04
Device: Nintendo Switch (switchroot)

I am unable to run any unity64 games with the latest version box64.I always get this message “please enable coredumps (ulimit -c unlimited) and restar” 

I need to switch to the old version three months ago to enter the game.(It shouldn't have been that long)

I don't know if anyone else has this problem.

**Comment by ruje0504** [comment] 2023-08-11 18:02
I received the same prompt as him.
I don't know if this issue should be merged.

https://github.com/ptitSeb/box64/issues/910

I received the same prompt using both Wine8.5 and wine 8.13&wine(wow64)8.13

**Comment by ptitSeb** [comment] 2023-08-11 18:12
you need to bisect box64 version to help narrow things down. Unity3D games runs on my side, and I don't have swtich, can't reproduce the issue on my side.

Also, you running Windows or Linux gmes?

**Comment by ruje0504** [comment] 2023-08-11 19:21
> you need to bisect box64 version to help narrow things down. Unity3D games runs on my side, and I don't have swtich, can't reproduce the issue on my side.
> 
> Also, you running Windows or Linux games?

yes,I will try

**Comment by ruje0504** [comment] 2023-08-11 21:51
> you need to bisect box64 version to help narrow things down. Unity3D games runs on my side, and I don't have swtich, can't reproduce the issue on my side.
> 
> Also, you running Windows or Linux games?

This issue started on July 22，2023 at 67c9378  ( 7ab299b is normal)

I am running Windows games.

**Comment by runlevel5** [comment] 2023-08-22 13:53
> How can I provide you with more information? Thank you

Compile with `cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo`, then use `gdb box64` and get the full backtrace when the game crashes. The backtrace would be extremely helpful for debugging

**Comment by ptitSeb** [comment] 2023-09-09 14:38
> 

Ok, thanks for  bisect. The result is surprising. Does this game have some anti-cheat feature? Or are you some some cheat engine maybe? I don't really see why this change would crash unity3d games (I certainly haven't seen that on my side).

**Comment by Pipetto-crypto** [comment] 2023-10-20 06:47
I am actually managing to reproduce this issue with this game's demo:

https://myosuki.itch.io/girls-girls-girls

Looking at a dump obtained with BOX64_DUMP, it seems to be hanging on these futex syscalls that it keeps repeating until wineserver crashes:

Calling libc syscall 0xCA (202) 0x123a60348 0x80 (nil) 0x12764fb00 (nil)
Calling libc syscall 0xCA (202) 0x123a60348 0x81 0x1 (nil) (nil)

I don't know if this is related but on wineserver side, it prints this:

0104: get_thread_context( handle=0160, context=0000, flags=00000003, native_flags=00000000, machine=8664)                                          

0110: *signal* signal=19                                                  

0104: get_thread_context() = ACCESS_VIOLATION { self=0, handle=0000, contexts={} }

**Comment by ptitSeb** [comment] 2023-10-20 11:14
did you used the windows version of the demo? because that ticket is about windows unity games.

**Comment by Pipetto-crypto** [comment] 2023-10-20 12:20
> did you used the windows version of the demo? because that ticket is about windows unity games.

Yes, of course else I wouldn't have replied here

**Comment by ptitSeb** [comment] 2023-10-20 14:47
Ok, I reproduce the issue! I'll work on a fix.

**Comment by ptitSeb** [comment] 2023-10-20 15:34
Ok, I have pushed a fix/workaround for this. It seems to work, but that might need some more testing....

If you can update and test with latest version.

**Comment by ruje0504** [comment] 2023-11-17 07:15
> Ok, I have pushed a fix/workaround for this. It seems to work, but that might need some more testing....
> 
> If you can update and test with latest version.

thank you

**Comment by ruje0504** [comment] 2023-11-17 07:38
> Ok, I have pushed a fix/workaround for this. It seems to work, but that might need some more testing....
> 
> If you can update and test with latest version.

Several Unity games on my device are running smoothly now. Thanks for fixing the issue!

**Closed** 2023-11-17 07:38 UTC
