### ISSUE TITLE
wine will crash(proot/debian/sid)

### ISSUE THREAD

**Issue by dontknowhy** [ptitSeb/box64#329] opened 2022-06-24 10:42 UTC
wine6.5 will stop(performance issue) when it's starting
all ways stop when starting conhost.exe

**Comment by ptitSeb** [comment] 2022-06-24 12:40
I don't understand what the issue is, what is happening and on what system you are on.

**Comment by dontknowhy** [comment] 2022-06-24 14:11
> I don't understand what the issue is, what is happening and on what system you are on.

i want to run wine64
but wine64 will work without the "MountMgr" service
and i shutdown the wine and start it again,wine will unable to start(always shows 
![Screenshot_20220624_221047.jpg](https://user-images.githubusercontent.com/85813508/175553364-02e940d9-6618-4094-9e0f-5530900c659f.jpg)")

**Comment by chungyuhoi** [comment] 2022-10-21 07:06
I recommend you to run wine3.9 without crashed. If you insist with wine6 or above, Just install box86 and box64, use instruction "box64 wine64 taskmgr &", it will stuck, then "pkill services", that's all.

**Comment by LukeShortCloud** [comment] 2024-11-01 14:30
The latest Box64 and Wine now work together. Use Box86 with Box86, Box64 with Wine WoW64, or Box64 with Box32 support enabled. Closing as resolved.

**Closed by LukeShortCloud** 2024-11-01 14:30 UTC
